[esp-wifi]
# Increase the default value to avoid "ERROR - RX QUEUE FULL" logs in runtime
# https://github.com/esp-rs/esp-wifi/issues/250#issuecomment-1694606068
# https://github.com/esp-rs/esp-wifi/issues/291
rx_queue_size = 15
